name: tieto-dev-maven # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Maven 3.5.2 # 79 char long summary
description: |
  Maven 3.5.2 for Tieto Java developers

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots

apps:
  hello:
    command: tieto-dev-maven

parts:
  tieto-dev-maven:
    plugin: autotools
    source: https://github.com/DanielAxelssonTieto/tieto-dev-maven-3.5.2/blob/master/apache-maven-3.5.2-bin%20.tar.gz
